<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorvooheader') ?>
<?php $legs = Data::get('legs')?>
<?php $aeroportos = Data::get('aeroporto') ?>

    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="../../../middleware/frontcontroller.php">Home</a></li>
            <li class="active">Leg Index</li>
        </ol>

        <h2 class="text-left top-space">Leg Index</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-120">
                <table class="table table-striped"><thead><th><h3>Origem</h3></th><th><h3>Destino</h3></th><th><h3>Data Partida</h3></th><th><h3>Data Chegada</h3></th><th><h3>Distancia</h3></th></thead>
                    <tbody>
                    <?php foreach ($legs as $leg) { ?>
                        <tr>
                            <td><?php
                                foreach ($aeroportos as $aeroporto) {
                                    if($leg->idaeroportoorigem == $aeroporto->id) {
                                        echo ' <option value=' . $aeroporto->id . '>' . $aeroporto->nome . '</option>';
                                    }
                                }?></td>
                            <td><?php
                                foreach ($aeroportos as $aeroporto) {
                                    if($leg->idaeroportodestino == $aeroporto->id) {
                                        echo ' <option value=' . $aeroporto->id . '>' . $aeroporto->nome . '</option>';
                                    }
                                }?></td>
                            <td><?=$leg->dateorigin->format('Y-m-d H:i:s')?></td>
                            <td><?=$leg->dateend->format('Y-m-d H:i:s')?></td>
                            <td><?=$leg->distancia?></td>
                            <td width="500">
                                <a href="<?=Url::toRoute('legs/edit', $leg->id)?>" class="btn btn-info" role="button">Edit</a>
                                <a href="<?=Url::toRoute('legs/destroy', $leg->id)?>" class="btn btn-warning" role="button">Delete</a>
                                <a href="<?=Url::toRoute('planelegs/create', $leg->idvoo)?>" class="btn btn-info" role="button">Assign Plane</a>
                            </td>
                        </tr>
                    <?php } ?>

                    </tbody>

                </table>

            </div>
            <div class="col-sm-6">
                <h3>Create a new Leg</h3>
                <p>
                    <a href="<?=Url::toRoute('legs/create')?>" class="btn btn-info" role="button">New</a>
                </p>
            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>