<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('adminheader') ?>
<?php $planes = Data::get('planes')?>
<?php ErrMgr::attach($planes) ?>

    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Edit Plane</h1>
                </header>

                <div class="panel panel-default">
                    <div class="panel-body">

                        <hr>

                        <form class="form-horizontal" method="post" action="<?=Url::toRoute('plane/update', $planes->id)?>">

                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Referencia:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" value="<?=$planes->referencia?>" class="form-control" required name="referencia">
                                    <?= ErrMgr::bind('referencia') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Lotação:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" value="<?=$planes->lotacao?>" class="form-control" required name="lotacao">
                                    <?= ErrMgr::bind('lotacao') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Tipo de Avião:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" value="<?=$planes->tipoaviao?>" class="form-control" required name="tipoaviao">
                                    <?= ErrMgr::bind('tipoaviao') ?>
                                </div>
                            </div>

                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-default" type="submit">Save</button>
                            </div>
                    </div>
                    </form>
                </div>
        </div>



        </article>
        <!-- /Article -->

    </div>
    </div>	<!-- /container -->
    <br><br><br><br><br><br><br>
<?php Layout::includeLayout('footer') ?>