<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('opcheckinheader') ?>
<?php $flightsales = Data::get('flightsales');
$flights = Data::get('flights');
?>

    <!-- container -->
    <div class="container">

        <?php
        echo ' <h2 class="text-left top-space"> Voo de ' .$flights->airportorigem->nome. ' - '.$flights->airportdestino->nome.'</h2>';
        ?>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped"><thead><th><h3>User</h3></th><th><h3>Preco Pago</h3></th><th><h3>Data Compra</h3></th></thead>
                    <tbody>
                    <?php foreach ($flightsales as $flightsale) { ?>
                        <tr>
                            <td><?=$flightsale->flightsuser->nome?></td>
                            <td><?=$flightsale->precopago?></td>
                            <td><?=$flightsale->datacompra->format('Y-m-d')?></td>
                            <td>
                                <a href="<?=Url::toRoute('opcheckin/store', $flightsale->id)?>" class="btn btn-info" role="button">Realizar CheckIn</a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>