<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('opcheckinheader') ?>
<?php $flights = Data::get('flights')?>

    <!-- container -->
    <div class="container">

        <h2 class="text-left top-space">Flights Index</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped"><thead><th><h3>Aeroporto Origem</h3></th><th><h3>Aeroporto Destino</h3></th></thead>
                    <tbody>
                    <?php foreach ($flights as $flight) { ?>
                        <tr>
                            <td><?=$flight->airportorigem->nome?></td>
                            <td><?=$flight->airportdestino->nome?></td>
                            <td>
                                <a href="<?=Url::toRoute('opcheckin/checkin', $flight->id)?>" class="btn btn-info" role="button">Realizar CheckIns</a>

                            </td>
                        </tr>
                    <?php } ?>

                    </tbody>

                </table>

            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>