<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('passageiroheader') ?>
<?php $flightsida = Data::get('flightsida');
$flightsvolta = Data::get('flightsvolta');
$flightsales = Data::get('flightsales');
?>
<!-- container -->
<div class="container">
    <div class="row">
        <h1>Bilhete: </h1>
        <div class="col-sm-12">

            <?php
            echo ' <h2 class="text-left top-space"> Voo de ' .$flightsida->airportorigem->nome. ' - '.$flightsida->airportdestino->nome.'</h2>';
            ?>

            <div class="col-sm-120">
                <table class="table table-striped"><thead><th><h3>Origem</h3></th><th><h3>Destino</h3></th><th><h3>Data Partida</h3></th><th><h3>Hora Partida</h3></th><th><h3>Data Chegada</h3></th><th><h3>Hora Chegada</h3></th><th><h3>Distancia</h3></th></thead>
                    <tbody>
                    <?php foreach ($flightsida->layovers as $flight) { ?>
                        <tr>
                            <td><?=$flight->airportorigem->nome?></td>
                            <td><?=$flight->airportdestino->nome?></td>
                            <td><?=$flight->dateorigin->format('Y-m-d')?></td>
                            <td><?=$flight->horaorigin?></td>
                            <td><?=$flight->dateend->format('Y-m-d')?></td>
                            <td><?=$flight->horaend?></td>
                            <td><?=$flight->distancia?></td>
                        </tr>
                    <?php } ?>

                    </tbody>

                </table>

            </div>
            <?php
            echo ' <h2 class="text-left top-space"> Voo de ' .$flightsvolta->airportorigem->nome. ' - '.$flightsvolta->airportdestino->nome.'</h2>';
            ?>
            <div class="col-sm-120">
                <table class="table table-striped"><thead><th><h3>Origem</h3></th><th><h3>Destino</h3></th><th><h3>Data Partida</h3></th><th><h3>Hora Partida</h3></th><th><h3>Data Chegada</h3></th><th><h3>Hora Chegada</h3></th><th><h3>Distancia</h3></th></thead>
                    <tbody>
                    <?php foreach ($flightsvolta->layovers as $flight) { ?>
                        <tr>
                            <td><?=$flight->airportorigem->nome?></td>
                            <td><?=$flight->airportdestino->nome?></td>
                            <td><?=$flight->dateorigin->format('Y-m-d')?></td>
                            <td><?=$flight->horaorigin?></td>
                            <td><?=$flight->dateend->format('Y-m-d')?></td>
                            <td><?=$flight->horaend?></td>
                            <td><?=$flight->distancia?></td>
                        </tr>
                    <?php } ?>

                    </tbody>

                </table>

            </div>

        </div>
        <br><br>
            <h2>
                <?php echo 'Preco Pago: '.$flightsales->precopago.' €' ?>
            </h2>
<br>
        <div class="col-sm-6">
            <br>
            <p>
                <a href="<?=Url::toRoute('passageiro/voos')?>" class="btn btn-info" role="button">Voltar</a>
            </p>
        </div>
    </div> <!-- /row -->

</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>
