<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('passageiroheader') ?>
<?php $flightsales = Data::get('flightsales');?>

    <!-- container -->
    <div class="container">

        <h2 class="text-left top-space">Historico de Voos</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped"><thead><th><h3>Voo Ida</h3></th><th><h3>Voo Volta</h3></th><th><h3>Preco Total</h3></th><th><h3>Data de Compra</h3></th></thead>
                    <tbody>
                    <?php foreach ($flightsales as $flightsale) { ?>
                        <tr>
                            <td><?=$flightsale->flightsaleida->airportorigem->nome. ' - '. $flightsale->flightsaleida->airportdestino->nome?></td>
                            <td><?=$flightsale->flightsalevolta->airportorigem->nome. ' - '. $flightsale->flightsalevolta->airportdestino->nome?></td>
                            <td><?=$flightsale->precopago.'€'?></td>
                            <td><?=$flightsale->datacompra->format('Y-m-d')?></td>
                            <td>
                                <!--<a href="<? /*=Url::toRoute('aeroporto/show', $aeroporto->id)?>" class="btn btn-info" role="button">Show</a> -->
                             <!--   <a href="<?/*=Url::toRoute('aeroporto/edit', $aeroporto->id)*/?>" class="btn btn-info" role="button">Edit</a>
                                <a href="<?/*=Url::toRoute('aeroporto/destroy', $aeroporto->id)*/?>" class="btn btn-warning" role="button">Delete</a>
                           --> </td>
                            <?php
                            \ArmoredCore\WebObjects\Debug::barDump($flightsale->flightsaleida->airportorigem->nome, 'hi'); ?>
                        </tr>
                    <?php }?>

                    </tbody>

                </table>
                <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>