<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('passageiroheader') ?>
<?php $passageiros = Data::get('user'); ?>

    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Passageiro Index</li>
        </ol>

        <h2 class="text-left top-space">Passageiro</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">

                <table class="table table-striped"><thead><th><h3>Nome</h3></th>
                    <th><h3>Morada</h3></th><th><h3>Email</h3></th><th><h3>Nif</h3></th><th><h3>Telefone</h3>
                    </th><th><h3>Password</h3></th></thead>
                    <tbody>

                        <tr>
                            <td><?=$passageiros->nome?></td>
                            <td><?=$passageiros->morada?></td>
                            <td><?=$passageiros->email?></td>
                            <td><?=$passageiros->nif?></td>
                            <td><?=$passageiros->telefone?></td>
                            <td><?=$passageiros->password?></td>
                            <td>
                                <a href="<?=Url::toRoute('passageiro/edit', $passageiros->id)?>" class="btn btn-info" role="button">Edit</a>
                            </td>
                        </tr>

                    </tbody>

                </table>

            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>