<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('passageiroheader') ?>
<?php $passageiros = Data::get('user'); ?>

    <!-- container -->
    <div class="container">

        <h2 class="text-left top-space">Passageiro</h2>
        <h2 class="top-space"></h2>

        <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form method="post" action="<?=Url::toRoute('passageiro/edit', $passageiros->id)?>">
                        <div class="top-margin">
                            <label>Nome <span class="text-danger">*</span></label>
                            <input readonly="true" type="text" value="<?=$passageiros->nome?>" name="nome" class="form-control">
                        </div>

                        <div class="top-margin">
                            <label>Morada <span class="text-danger">*</span></label>
                            <input readonly="true" type="text" value="<?=$passageiros->morada?>" name="morada" class="form-control">
                        </div>

                        <div class="top-margin">
                            <label>Email <span class="text-danger">*</span></label>
                            <input readonly="true" type="text" value="<?=$passageiros->email?>" name="email" class="form-control">
                        </div>

                        <div class="top-margin">
                            <label>Nif <span class="text-danger">*</span></label>
                            <input readonly="true" type="text" value="<?=$passageiros->nif?>" name="nif" class="form-control">
                        </div>

                        <div class="top-margin">
                            <label>Telefone <span class="text-danger">*</span></label>
                            <input readonly="true" type="text" value="<?=$passageiros->telefone?>" name="telefone" class="form-control">
                        </div>

                        <div class="top-margin">
                            <label>Username <span class="text-danger">*</span></label>
                            <input readonly="true" type="text" value="<?=$passageiros->username?>" name="username" class="form-control">
                        </div>

                        <div class="top-margin">
                            <label>Password <span class="text-danger">*</span></label>
                            <input readonly="true" type="text" value="<?=$passageiros->password?>" name="password" class="form-control">
                        </div>

                        <br>
                        <div class="col-lg-4 text-right">
                            <button class="btn btn-action" type="submit">Alterar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>


    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>