<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('passageiroheader') ?>
<?php $layovers = Data::get('layover'); ?>
<?php $airports = Data::get('airport'); ?>

    <!-- container -->
    <div class="container">
        <h2 class="text-left top-space">Tabela de Voos</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">

                <table class="table table-striped">

                    <div class="top-margin">
                            <div style="display: inline-block" >
                                <form method="post" action="<?=Url::toRoute('passageiro/selectdropdownorigem')?>">
                                    <label>Aeroporto Origem <span class="text-danger">*</span></label>
                                        <select name="idorigem" class="form-control">
                                            <option selected value="0"> -- Selecione uma Opção -- </option>
                                            <?php
                                                foreach ($airports as $airport) {
                                                    echo ' <option value='.$airport->id.'>'.$airport->nome.'</option>';
                                                }
                                            ?>
                                        </select>
                                    <br>
                                        <div class="row">
                                            <div class="col-lg-4 text-middle">
                                                <button class="btn btn-action" type="submit">Search</button>
                                            </div>
                                        </div>
                                </form>
                            </div>
                        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                        <div style="display: inline-block" >
                            <form method="post" action="<?=Url::toRoute('passageiro/selectdropdowndestino')?>">
                                <label  style ="padding = 15px ">Aeroporto Destino <span class="text-danger">*</span></label>
                                <select name="iddestino" class="form-control">
                                    <option selected value="0"> -- Selecione uma Opção -- </option>
                                    <?php
                                    foreach ($airports as $airport) {
                                        echo ' <option value='.$airport->id.'>'.$airport->nome.'</option>';
                                    }
                                    ?>
                                </select>
                                <br>
                                <div class="row">
                                    <div class="col-lg-4 text-middle">
                                        <button class="btn btn-action" type="submit">Search</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                            <div style="display: inline-block" >
                        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                        <div style="display: inline-block" >
                            <form method="post" action="<?=Url::toRoute('passageiro/voos')?>">
                                <div class="row">
                                    <div class="col-lg-4 text-middle">
                                        <button class="btn btn-action" type="submit">Clear</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <br>


                    <thead><th><h3>Aeroporto Origem</h3></th><th><h3>Aeroporto Destino</h3></th><th><h3>Data Partida</h3></th></th><th><h3>Hora Partida</h3></th><th><h3>Data Chegada</h3>
                    </th><th><h3>Hora Chegada</h3></th></th><th><h3>Distancia</h3></th></th></thead>

                    <tbody>
                    <?php foreach ($layovers as $layover) { ?>
                    <tr>
                        <td><?=$layover->airportorigem->nome?></td>
                        <td><?=$layover->airportdestino->nome?></td>
                        <td><?=$layover->dateorigin->format('Y-m-d')?></td>
                        <td><?=$layover->horaorigin?></td>
                        <td><?=$layover->dateend->format('Y-m-d')?></td>
                        <td><?=$layover->horaend?></td>
                        <td><?=$layover->distancia?></td>
                    </tr>
                    <?php } ?>
                    </tbody>

                </table>

            </div>
            <div class="col-sm-6">
                <br>
                <p>
                    <a href="<?=Url::toRoute('passageiro/compra')?>" class="btn btn-info" role="button">Simulamento de uma Passagem</a>
                </p>
            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>