<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorvooheader') ?>
<?php $legs = Data::get('layover') ?>
<?php $flights = Data::get('flights') ?>
<?php $aeroportos = Data::get('aeroporto') ?>
<?php ErrMgr::attach($legs) ?>

    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">New Leg</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">

                            <form method="post" action="<?=Url::toRoute('layover/store')?>">
                                <div class="top-margin">
                                    <label>Voo <span class="text-danger">*</span></label>
                                    <select name="idvoo" class="form-control">
                                        <?php
                                        foreach ($flights as $flight) {
                                            echo ' <option value='.$flight->id.'>'.$flight->id.'</option>';
                                        }
                                        ?>
                                    </select>
                                    <?= ErrMgr::bind('idvoo') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Aeroporto Destino <span class="text-danger">*</span></label>
                                    <select name="idaeroportodestino" class="form-control">
                                        <?php
                                        foreach ($aeroportos as $aeroporto) {
                                            echo ' <option value='.$aeroporto->id.'>'.$aeroporto->nome.'</option>';
                                        }
                                        ?>
                                    </select>
                                    <?= ErrMgr::bind('idaeroportodestino') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Aeroporto Origem <span class="text-danger">*</span></label>
                                    <select name="idaeroportoorigem" class="form-control">
                                        <?php
                                        foreach ($aeroportos as $aeroporto) {
                                            echo ' <option value='.$aeroporto->id.'>'.$aeroporto->nome.'</option>';
                                        }
                                        ?>
                                    </select>
                                    <?= ErrMgr::bind('idaeroportoorigem') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Data de Origem <span class="text-danger">*</span></label>
                                    <input type="date" value="<?= $legs->dateorigin?>" name="dateorigin" class="form-control" placeholder="Introduza a data">
                                    <?= ErrMgr::bind('dateorigin') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Hora de Origem <span class="text-danger">*</span></label>
                                    <input type="time" value="<?= $legs->horaorigin?>" name="horaorigin" class="form-control" placeholder="Introduza a data">
                                    <?= ErrMgr::bind('horaorigin') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Data de Chegada <span class="text-danger">*</span></label>
                                    <input type="date" value="<?= $legs->dateend?>" name="dateend" class="form-control" placeholder="Introduza a data">
                                    <?= ErrMgr::bind('dateend') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Hora de Chegada <span class="text-danger">*</span></label>
                                    <input type="time" value="<?= $legs->horaend?>" name="horaend" class="form-control" placeholder="Introduza a data">
                                    <?= ErrMgr::bind('horaend') ?>
                                </div>


                                <div class="top-margin">
                                    <label>Distancia <span class="text-danger">*</span></label>
                                    <input type="text" value="<?= $legs->distancia?>" name="distancia" class="form-control" placeholder="Introduza a distancia">
                                    <?= ErrMgr::bind('distancia') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Numero de Ordem <span class="text-danger">*</span></label>
                                    <input type="text" value="<?= $legs->numordem?>" name="numordem" class="form-control" placeholder="Introduza o numOrdem">
                                    <?= ErrMgr::bind('numOrdem') ?>
                                </div>


                                <div class="row">
                                    <div class="col-lg-4 text-middle">
                                        <button class="btn btn-action" type="submit">Introduzir Flight</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>