<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorvooheader') ?>
<?php $flights = Data::get('flights')?>
<?php $aeroportos = Data::get('aeroporto') ?>

    <!-- container -->
    <div class="container">

        <?php
            foreach ($aeroportos as $aeroporto){
                if($aeroporto->id == $flights->idaeroporto) {
                    echo ' <h2 class="text-left top-space"> Voos de ' .$aeroporto->nome. '</h2>';
                }
            }
        ?>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-120">
                <table class="table table-striped"><thead><th><h3>Destino</h3></th><th><h3>Data Partida</h3></th><th><h3>Hora Partida</h3></th><th><h3>Data Chegada</h3></th><th><h3>Hora Chegada</h3></th><th><h3>Distancia</h3></th></thead>
                    <tbody>
                    <?php foreach ($flights->layovers as $flight) { ?>
                        <tr>
                            <td><?=$flight->airportdestino->nome?></td>
                            <td><?=$flight->dateorigin->format('Y-m-d')?></td>
                            <td><?=$flight->dateend->format('Y-m-d')?></td>
                            <td><?=$flight->horaorigin?></td>
                            <td><?=$flight->horaend?></td>
                            <td><?=$flight->distancia?></td>
                            <td width="500">
                                <a href="<?=Url::toRoute('layover/edit', $flight->id)?>" class="btn btn-info" role="button">Edit</a>
                                <a href="<?=Url::toRoute('layover/destroy', $flight->id)?>" class="btn btn-warning" role="button">Delete</a>
                                <a href="<?=Url::toRoute('layoverplanes/create', $flight->id)?>" class="btn btn-info" role="button">Assign Plane</a>
                            </td>
                        </tr>
                    <?php } ?>

                    </tbody>

                </table>

            </div>
            <div class="col-sm-6">
                <h3>Nova Escala</h3>
                <p>
                    <a href="<?=Url::toRoute('layover/create' , $flight->idvoo)?>" class="btn btn-info" role="button">New</a>
                </p>
            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>