<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('adminheader') ?>
<?php $user = Data::get('user') ?>
<?php ErrMgr::attach($user) ?>

    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">New User</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">

                            <form method="post" action="<?=Url::toRoute('user/store')?>">
                                <div class="top-margin">
                                    <label>Nome <span class="text-danger">*</span></label>
                                    <input type="text" value="<?= $user->nome ?>" name="nome" class="form-control">
                                    <?= ErrMgr::bind('nome') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Morada <span class="text-danger">*</span></label>
                                    <input type="text" value="<?= $user->morada ?>" name="morada" class="form-control">
                                    <?= ErrMgr::bind('morada') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Email <span class="text-danger">*</span></label>
                                    <input type="text" value="<?= $user->email ?>" name="email" class="form-control">
                                    <?= ErrMgr::bind('email') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Nif <span class="text-danger">*</span></label>
                                    <input type="text" value="<?= $user->nif ?>" name="nif" class="form-control">
                                    <?= ErrMgr::bind('nif') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Telefone <span class="text-danger">*</span></label>
                                    <input type="text" value="<?= $user->telefone ?>" name="telefone" class="form-control">
                                    <?= ErrMgr::bind('telefone') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Username <span class="text-danger">*</span></label>
                                    <input type="text" value="<?= $user->username ?>" name="username" class="form-control">
                                    <?= ErrMgr::bind('username') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Password <span class="text-danger">*</span></label>
                                    <input type="text" value="<?= $user->password ?>" name="password" class="form-control">
                                    <?= ErrMgr::bind('password') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Role <span class="text-danger">*</span></label>
                                    <select name="role" class="form-control">
                                        <option value="admin">admin</option>
                                        <option value="opcheckin">opcheckin</option>
                                        <option value="gestorvoo">gestorvoo</option>
                                        <option value="passageiro">passageiro</option>
                                    </select>
                                    <?= ErrMgr::bind('role') ?>
                                </div>

                                <hr>

                                <div class="row">
                                    <div class="col-lg-4 text-middle">
                                        <button class="btn btn-action" type="submit">Introduzir User</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>