<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('adminheader') ?>
<?php $user = Data::get('user');
ErrMgr::attach($user) ?>

    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Edit User</h1>
                </header>

                <div class="panel panel-default">
                    <div class="panel-body">

                        <hr>

                        <form class="form-horizontal" method="post" action="<?=Url::toRoute('user/update', $user->id)?>">

                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Nome:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" value="<?=$user->nome?>" class="form-control" required name="nome" placeholder="Nome">
                                    <?= ErrMgr::bind('nome') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Morada:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" value="<?=$user->morada?>" class="form-control" required name="morada" placeholder="Morada">
                                    <?= ErrMgr::bind('morada') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Email:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" value="<?=$user->email?>" class="form-control" required name="email" placeholder="Email">
                                    <?= ErrMgr::bind('email') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Nif:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" value="<?=$user->nif?>" class="form-control" required name="nif" placeholder="Nif">
                                    <?= ErrMgr::bind('nif') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Telefone:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" value="<?=$user->telefone?>" class="form-control" required name="telefone" placeholder="Telefone">
                                    <?= ErrMgr::bind('telefone') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Role:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <select class="form-control" required name="role" placeholder="Role">
                                        <option value="admin">admin</option>
                                        <option value="opcheckin">opcheckin</option>
                                        <option value="gestorvoo">gestorvoo</option>
                                        <option value="passageiro">passageiro</option>
                                    </select>
                                    <?= ErrMgr::bind('role') ?>
                                </div>
                            </div>
                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-default" type="submit">Save</button>
                            </div>
                    </div>
                    </form>
                </div>
        </div>



        </article>
        <!-- /Article -->

    </div>
    </div>	<!-- /container -->
    <br><br><br><br><br><br><br>
<?php Layout::includeLayout('footer') ?>