<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('adminheader') ?>
<?php $user = Data::get('user');
?>

    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">User</li>
        </ol>

        <h2 class="text-left top-space">User Management</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped"><thead><th><h3>Id</h3></th><th><h3>Nome</h3></th>
                    <th><h3>Morada</h3></th><th><h3>Email</h3></th><th><h3>Nif</h3></th><th><h3>Telefone</h3>
                    </th><th><h3>Role</h3></th></thead>
                    <tbody>
                    <?php foreach ($user as $userInfo) { ?>
                        <tr>
                            <td><?=$userInfo->id?></td>
                            <td><?=$userInfo->nome?></td>
                            <td><?=$userInfo->morada?></td>
                            <td><?=$userInfo->email?></td>
                            <td><?=$userInfo->nif?></td>
                            <td><?=$userInfo->telefone?></td>
                            <td><?=$userInfo->role?></td>
                            <td>
                                <!--<a href="<?/*=Url::toRoute('aeroporto/show', $opcheck->id)*/?>" class="btn btn-info" role="button">Show</a> -->
                            <a href="<?=Url::toRoute('user/edit', $userInfo->id)?>" class="btn btn-info" role="button">Edit</a>
                                <a href="<?=Url::toRoute('user/destroy', $userInfo->id)?>" class="btn btn-warning" role="button">Delete</a>
                            </td>
                        </tr>
                    <?php } ?>

                    </tbody>

                </table>

            </div>
            <div class="col-sm-6">
                <h3>Create a new User</h3>
                <p>
                    <a href="<?=Url::toRoute('user/create')?>" class="btn btn-info" role="button">New</a>
                </p>
            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>