<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $user = Data::get('user') ?>

    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">View Aeroporto</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <hr>

                            <form method="post" action="<?=Url::toRoute('user/index')?>">
                                <div class="top-margin">
                                    <label>Nome <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$user->nome?>" name="nome" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Cidade <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$user->cidade?>" name="cidade" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Pais <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$user->pais?>" name="pais" class="form-control">
                                </div>

                                <hr>

                                <div class="col-lg-4 text-right">
                                    <button class="btn btn-action" type="submit">Return</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>