<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorvooheader') ?>
<?php $flight = Data::get('flights') ?>
<?php $aeroportos = Data::get('aeroporto') ?>
<?php ErrMgr::attach($flight) ?>

    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">New Flight</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">

                            <form method="post" action="<?=Url::toRoute('flights/store')?>">
                                <div class="top-margin">
                                    <label>Aeroporto <span class="text-danger">*</span></label>
                                    <select name="idaeroportoorigem" class="form-control">
                                        <?php
                                            foreach ($aeroportos as $aeroporto) {
                                                echo ' <option value='.$aeroporto->id.'>'.$aeroporto->nome.'</option>';
                                            }
                                        ?>
                                    </select>
                                    <?= ErrMgr::bind('idaeroportoorigem') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Aeroporto <span class="text-danger">*</span></label>
                                    <select name="idaeroportodestino" class="form-control">
                                        <?php
                                        foreach ($aeroportos as $aeroporto) {
                                            echo ' <option value='.$aeroporto->id.'>'.$aeroporto->nome.'</option>';
                                        }
                                        ?>
                                    </select>
                                    <?= ErrMgr::bind('idaeroportodestino') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Preco Venda <span class="text-danger">*</span></label>
                                    <input type="text" value="<?= $flight->precoVenda ?>" name="precovenda" class="form-control">
                                    <?= ErrMgr::bind('precoVenda') ?>
                                </div>

                                <hr>

                                <div class="row">
                                    <div class="col-lg-4 text-middle">
                                        <button class="btn btn-action" type="submit">Introduzir Flight</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>