<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorvooheader') ?>
<?php $flights = Data::get('flights')?>

    <!-- container -->
    <div class="container">

        <h2 class="text-left top-space">Flights Index</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped"><thead><th><h3>Id</h3></th><th><h3>Aeroporto Origem</h3></th><th><h3>Aeroporto Destino</h3></th><th><h3>precoVenda</h3></th></thead>
                    <tbody>
                    <?php foreach ($flights as $flight) { ?>
                        <tr>
                            <td><?=$flight->id?></td>
                            <td><?=$flight->airportorigem->nome?></td>
                            <td><?=$flight->airportdestino->nome?></td>
                            <td><?=$flight->precovenda?></td>
                            <td>
                                <!--<a href="<?=Url::toRoute('flight/show', $flight->id)?>" class="btn btn-info" role="button">Show</a> -->
                                <a href="<?=Url::toRoute('flights/edit', $flight->id)?>" class="btn btn-info" role="button">Edit</a>
                                <a href="<?=Url::toRoute('flights/destroy', $flight->id)?>" class="btn btn-warning" role="button">Delete</a>
                                <a href="<?=Url::toRoute('layover/index', $flight->id)?>" class="btn btn-info" role="button">Gerir Escalas</a>

                            </td>
                        </tr>
                    <?php } ?>

                    </tbody>

                </table>

            </div>
            <div class="col-sm-6">
                <h3>Create a new Flight</h3>
                <p>
                    <a href="<?=Url::toRoute('flights/create')?>" class="btn btn-info" role="button">New</a>
                </p>
            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>