<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorvooheader') ?>
<?php $planelegs = Data::get('layoverplanes') ?>
<?php $layover = Data::get('layover') ?>
<?php $planes = Data::get('planes') ?>
<?php ErrMgr::attach($planelegs);
?>

    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Assign Plane</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">

                            <form method="post" action="<?=Url::toRoute('layoverplanes/store')?>">
                                <div class="top-margin">
                                    <label>Voo <span class="text-danger">*</span></label>
                                    <select name="idescala" class="form-control">
                                        <option value=<?= $layover->id ?>><?= $layover->id ?></option>
                                    </select>
                                    <?= ErrMgr::bind('idescala') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Aviao <span class="text-danger">*</span></label>
                                    <select name="idaviao" class="form-control">
                                        <?php
                                        foreach ($planes as $plane) {
                                            echo ' <option value='.$plane->id.'>'.$plane->referencia.'</option>';
                                        }
                                        ?>
                                    </select>
                                    <?= ErrMgr::bind('idaviao') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Numero Passageiros <span class="text-danger">*</span></label>
                                        <input type="text" value="<?= $planelegs->numpassageiros?>" name="numpassageiros" class="form-control" placeholder="Introduza o numero de passageiros">
                                    <?= ErrMgr::bind('numpassageiros') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Numero de Bilhetes Vendidos <span class="text-danger">*</span></label>
                                    <input type="text" value="<?= $planelegs->numbilhetesvendidos?>" name="numbilhetesvendidos" class="form-control" placeholder="Introduza o numero de bilhetes vendidos">
                                    <?= ErrMgr::bind('numbilhetesvendidos') ?>
                                </div>
                                <br>
                                <div class="row">
                                    <div class="col-lg-4 text-middle">
                                        <button class="btn btn-action" type="submit">Introduzir Plane Leg</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>